// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.DataAccess;

#nullable disable

namespace UrlShortener.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113225128_UpdateShortLink")]
    partial class UpdateShortLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.LinkClickDbTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShortLinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShortLinkId");

                    b.ToTable("LinkClicks");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.PlanDbTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CustomAliasEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLinksPerMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("numeric");

                    b.Property<bool>("QrEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.QrCodeDbTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShortLinkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShortLinkId")
                        .IsUnique();

                    b.ToTable("QrCodes");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.ShortLinkDbTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalClicks")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShortLinks");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.SubscriptionDbTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.UserDbTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.LinkClickDbTable", b =>
                {
                    b.HasOne("UrlShortener.DataAccess.Entities.ShortLinkDbTable", "ShortLink")
                        .WithMany("LinkClicks")
                        .HasForeignKey("ShortLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortLink");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.QrCodeDbTable", b =>
                {
                    b.HasOne("UrlShortener.DataAccess.Entities.ShortLinkDbTable", "ShortLink")
                        .WithOne("QrCode")
                        .HasForeignKey("UrlShortener.DataAccess.Entities.QrCodeDbTable", "ShortLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortLink");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.ShortLinkDbTable", b =>
                {
                    b.HasOne("UrlShortener.DataAccess.Entities.UserDbTable", "User")
                        .WithMany("ShortLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.SubscriptionDbTable", b =>
                {
                    b.HasOne("UrlShortener.DataAccess.Entities.PlanDbTable", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrlShortener.DataAccess.Entities.UserDbTable", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.PlanDbTable", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.ShortLinkDbTable", b =>
                {
                    b.Navigation("LinkClicks");

                    b.Navigation("QrCode");
                });

            modelBuilder.Entity("UrlShortener.DataAccess.Entities.UserDbTable", b =>
                {
                    b.Navigation("ShortLinks");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
